plugins {
    id 'maven-publish'
    id 'dev.architectury.loom' version '1.13-SNAPSHOT' apply false

    // https://github.com/ReplayMod/preprocessor
    // https://github.com/Fallen-Breath/preprocessor
    id 'com.replaymod.preprocess' version 'd452ef7612'

    // https://github.com/Fallen-Breath/yamlang
    id 'me.fallenbreath.yamlang' version '1.5.0'
}

preprocess {
    strictExtraMappings = false

    def mc116_fabric = createNode('1.16.5-fabric', 1_16_05, '')
    def mc117_fabric = createNode('1.17.1-fabric', 1_17_01, '')
    def mc118_fabric = createNode('1.18.2-fabric', 1_18_02, '')
    def mc119_fabric = createNode('1.19.4-fabric', 1_19_04, '')
    def mc12001_fabric = createNode('1.20.1-fabric', 1_20_01, '')
    def mc12004_fabric = createNode('1.20.4-fabric', 1_20_04, '')
    def mc12006_fabric = createNode('1.20.6-fabric', 1_20_06, '')
    def mc12101_fabric = createNode('1.21.1-fabric', 1_21_01, '')
    def mc12104_fabric = createNode('1.21.4-fabric', 1_21_04, '')
    def mc12105_fabric = createNode('1.21.5-fabric', 1_21_05, '')
    def mc12108_fabric = createNode('1.21.8-fabric', 1_21_08, '')
    def mc12110_fabric = createNode('1.21.10-fabric', 1_21_10, '')
    def mc12111_fabric = createNode('1.21.11-fabric', 1_21_11, '')
    def mc12006_neoforge = createNode('1.20.6-neoforge', 1_20_06, '')
    def mc12101_neoforge = createNode('1.21.1-neoforge', 1_21_01, '')
    def mc12104_neoforge = createNode('1.21.4-neoforge', 1_21_04, '')
    def mc12105_neoforge = createNode('1.21.5-neoforge', 1_21_05, '')
    def mc12108_neoforge = createNode('1.21.8-neoforge', 1_21_08, '')
    def mc12110_neoforge = createNode('1.21.10-neoforge', 1_21_10, '')
    def mc12111_neoforge = createNode('1.21.11-neoforge', 1_21_11, '')

    mc116_fabric.link(mc117_fabric, null)
    mc117_fabric.link(mc118_fabric, null)
    mc118_fabric.link(mc119_fabric, null)
    mc119_fabric.link(mc12001_fabric, null)
    mc12001_fabric.link(mc12004_fabric, null)
    mc12004_fabric.link(mc12006_fabric, null)
    mc12006_fabric.link(mc12101_fabric, null)
    mc12101_fabric.link(mc12104_fabric, null)
    mc12104_fabric.link(mc12105_fabric, null)
    mc12105_fabric.link(mc12108_fabric, null)
    mc12108_fabric.link(mc12110_fabric, null)
    mc12110_fabric.link(mc12111_fabric, null)

    mc12006_fabric.link(mc12006_neoforge, null)
    mc12101_fabric.link(mc12101_neoforge, null)
    mc12104_fabric.link(mc12104_neoforge, null)
    mc12105_fabric.link(mc12105_neoforge, null)
    mc12108_fabric.link(mc12108_neoforge, null)
    mc12110_fabric.link(mc12110_neoforge, null)
    mc12111_fabric.link(mc12111_neoforge, null)
}

tasks.register('buildAndGather') {
    subprojects {
        dependsOn project.tasks.named('build').get()
    }
    doFirst {
        println 'Gathering builds'
        def buildLibs = {
            p -> p.buildDir.toPath().resolve('libs')
        }
        delete fileTree(buildLibs(rootProject)) {
            include '*'
        }
        subprojects {
            copy {
                from(buildLibs(project)) {
                    include '*.jar'
                    exclude '*-dev.jar', '*-sources.jar', '*-shadow.jar'
                }
                into buildLibs(rootProject).resolve('v' + project.mod_version)
                duplicatesStrategy   DuplicatesStrategy.INCLUDE
            }
            delete(buildLibs(project))
        }
    }
}
