# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
# Fabric Properties
# check these on https://fabricmc.net/develop
loader_version=0.18.5
# Mod Properties
mod_id=chattools
mod_version=2.4.2
maven_group=net.apple70cents
archives_base_name=chattools

# but I want to use Groovy anyway
dev.kikugie.stonecutter.hard_mode=true