pluginManagement {
	repositories {
		maven {
			name = 'Fabric'
			url = 'https://maven.fabricmc.net/'
		}
		maven {
			name = 'Jitpack'
			url = "https://jitpack.io"
		}
		maven {
			name = 'Architectury'
			url = "https://maven.architectury.dev/"
		}
		maven {
			name = 'Forge'
			url = "https://files.minecraftforge.net/maven/"
		}
		maven {
			name = 'KikuGie Snapshots'
			url = "https://maven.kikugie.dev/snapshots"
		}
		mavenCentral()
		gradlePluginPortal()
	}
}

plugins {
	id("dev.kikugie.stonecutter").version "0.9"
}

stonecutter {
	kotlinController = false
	centralScript = "build.gradle"

	create getRootProject(), {
		// Fabric versions
		version '1.16.5-fabric', '1.16.5'
		version '1.17.1-fabric', '1.17.1'
		version '1.18.2-fabric', '1.18.2'
		version '1.19.4-fabric', '1.19.4'
		version '1.20.1-fabric', '1.20.1'
		version '1.20.4-fabric', '1.20.4'
		version '1.20.6-fabric', '1.20.6'
		version '1.21.1-fabric', '1.21.1'
		version '1.21.4-fabric', '1.21.4'
		version '1.21.5-fabric', '1.21.5'
		version '1.21.8-fabric', '1.21.8'
		version '1.21.10-fabric', '1.21.10'
		version '1.21.11-fabric', '1.21.11'
		version '26.1.2-fabric', '26.1.2'

		// NeoForge versions
		version '1.20.6-neoforge', '1.20.6'
		version '1.21.1-neoforge', '1.21.1'
		version '1.21.4-neoforge', '1.21.4'
		version '1.21.5-neoforge', '1.21.5'
		version '1.21.8-neoforge', '1.21.8'
		version '1.21.10-neoforge', '1.21.10'
		version '1.21.11-neoforge', '1.21.11'
		version '26.1.2-neoforge', '26.1.2'

		vcsVersion = '26.1.2-neoforge'
	}
}
