modLoader = "javafml"
loaderVersion = "[1,)"
license = "GPL-3.0"
issueTrackerURL = "https://github.com/70CentsApple/ChatTools/issues"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "Chat Tools"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/chat-tools"
authors = "70CentsApple"
credits = '''\n
Litwak913
WhiteXero
As_One
en_us translation: UltimatChamp, 70CentsApple
zh_cn translation: 70CentsApple
zh_tw translation: yichifauzi
es_es translation: pilahito
ja_jp translation: wancor1
'''
description = '''
A toolkit that provides great chat-related features.
'''
logoFile = "icon.png"

[[dependencies."${id}"]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_dependency}"
ordering = "NONE"
side = "CLIENT"

[[dependencies."${id}"]]
modId = "cloth_config"
type = "required"
versionRange = "[0.0.1,)"
ordering = "NONE"
side = "CLIENT"

[[mixins]]
config = "${id}.mixins.json"
