# Fabric Properties
minecraft_version=1.21.5
# https://parchmentmc.org/docs/getting-started
parchment_version=2025.06.15
loom.platform = neoforge
# Mod Metadata
# https://projects.neoforged.net/neoforged/neoforge
neoforge_version = 21.5.95
minecraft_dependency = [1.21, 1.22)
# Dependencies
cloth_config_version=18.0.145
yacl_version=3.8.2+1.21.5