# Fabric Properties
minecraft_version=26.2
# https://parchmentmc.org/docs/getting-started
parchment_version=
loom.platform=fabric
# Fabric Mod Metadata
minecraft_dependency=26.2
# Dependencies
fabric_api_version=0.152.1+26.2
cloth_config_version=26.2.155
yacl_version=3.9.4+26.2
mod_menu_version=20.0.0-beta.2
