# Fabric Properties
minecraft_version=26.1
# https://parchmentmc.org/docs/getting-started
parchment_version=
loom.platform=neoforge
# Mod Metadata
# https://projects.neoforged.net/neoforged/neoforge
neoforge_version=26.1.0.5-beta
minecraft_dependency=[26.1, 26.2)
# Dependencies
cloth_config_version=26.1.154
