# Fabric Properties
minecraft_version=26.2
# https://parchmentmc.org/docs/getting-started
parchment_version=
loom.platform=neoforge
# Mod Metadata
# https://projects.neoforged.net/neoforged/neoforge
neoforge_version=26.2.0.1-beta
minecraft_dependency=[26.2, 26.3)
# Dependencies
cloth_config_version=26.2.155
yacl_version=3.9.4+26.2
