# Fabric Properties
minecraft_version=1.21.10
# https://parchmentmc.org/docs/getting-started
parchment_version=2025.10.12
loom.platform = neoforge
# Mod Metadata
# https://projects.neoforged.net/neoforged/neoforge
neoforge_version = 21.10.16-beta
minecraft_dependency = [1.21, 1.22)
# Dependencies
cloth_config_version=20.0.148
