# Fabric Properties
minecraft_version=26.1
# https://parchmentmc.org/docs/getting-started
parchment_version=
loom.platform=fabric
# Fabric Mod Metadata
minecraft_dependency=26.1
# Dependencies
fabric_api_version=0.144.3+26.1
cloth_config_version=26.1.154
yacl_version=3.9.1+26.1
mod_menu_version=18.0.0-alpha.8
