name: Release to Modrinth and Curseforge and GitHub

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-summary-and-github-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Build
        uses: ./.github/actions/build_artifacts/

      - name: Generate summary
        uses: ./.github/actions/summary/

      - name: Get variables
        run: |
          raw_file_paths=$(ls ./gathered-artifacts/*)
          # adds line breaks
          file_paths=${raw_file_paths//$'\n'/,}
          echo "file_paths=${file_paths}" >> $GITHUB_ENV

          raw_tag_name=${GITHUB_REF#refs/tags/}
          # removes the 'v' prefix
          tag_name=${raw_tag_name#v}
          echo "tag_name=${tag_name}" >> $GITHUB_ENV

          changelog=$(cat changelog.md)
          echo "changelog<<EOF" >> $GITHUB_ENV
          echo "${changelog}" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          repository: 70CentsApple/ChatTools
          tag_name: "v${{ env.tag_name }}"
          name: "v${{ env.tag_name }}"
          body: ${{ env.changelog }}
          draft: false
          prerelease: false
          generate_release_notes: true
          files: ${{ env.file_paths }}

      - name: Fetch Release Notes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          echo "Fetching release notes from GitHub..."
          gh release view "v${{ env.tag_name }}" --repo ${{ github.repository }} --json body --jq '.body' > release_notes.md

      - name: Upload Release Notes
        uses: actions/upload-artifact@v4
        with:
          name: Release Notes
          path: release_notes.md

  modrinth-and-curseforge-release:
    needs:
      - build-and-summary-and-github-release
    runs-on: ubuntu-latest
    strategy:
      # to ensure uploads are done sequentially
      max-parallel: 1
      matrix:
        include:
          # --- 26.x ---
          - artifact: "26.1.2-fabric"
            target_game_versions: "26.1,26.1.1,26.1.2"
            target_game_versions_cf_ids: "15933,16021,16082"
            formatted_version_name: "26.1(.x)"
            modloader: "fabric"

          - artifact: "26.1.2-neoforge"
            target_game_versions: "26.1,26.1.1,26.1.2"
            target_game_versions_cf_ids: "15933,16021,16082"
            formatted_version_name: "26.1(.x)"
            modloader: "neoforge"

          # --- 1.21.x ---
          - artifact: "1.21.11-fabric"
            target_game_versions: "1.21.11"
            target_game_versions_cf_ids: "14406"
            formatted_version_name: "1.21.11"
            modloader: "fabric"

          - artifact: "1.21.11-neoforge"
            target_game_versions: "1.21.11"
            target_game_versions_cf_ids: "14406"
            formatted_version_name: "1.21.11"
            modloader: "neoforge"

          - artifact: "1.21.10-fabric"
            target_game_versions: "1.21.9,1.21.10"
            target_game_versions_cf_ids: "13927,13964"
            formatted_version_name: "1.21.9(10)"
            modloader: "fabric"

          - artifact: "1.21.10-neoforge"
            target_game_versions: "1.21.9,1.21.10"
            target_game_versions_cf_ids: "13927,13964"
            formatted_version_name: "1.21.9(10)"
            modloader: "neoforge"

          - artifact: "1.21.8-fabric"
            target_game_versions: "1.21.6,1.21.7,1.21.8"
            target_game_versions_cf_ids: "13422,13506,13620"
            formatted_version_name: "1.21.6(7,8)"
            modloader: "fabric"

          - artifact: "1.21.8-neoforge"
            target_game_versions: "1.21.6,1.21.7,1.21.8"
            target_game_versions_cf_ids: "13422,13506,13620"
            formatted_version_name: "1.21.6(7,8)"
            modloader: "neoforge"

          - artifact: "1.21.5-fabric"
            target_game_versions: "1.21.5"
            target_game_versions_cf_ids: "12934"
            formatted_version_name: "1.21.5"
            modloader: "fabric"

          - artifact: "1.21.5-neoforge"
            target_game_versions: "1.21.5"
            target_game_versions_cf_ids: "12934"
            formatted_version_name: "1.21.5"
            modloader: "neoforge"

          - artifact: "1.21.4-fabric"
            target_game_versions: "1.21.2,1.21.3,1.21.4"
            target_game_versions_cf_ids: "12079,12084,12281"
            formatted_version_name: "1.21.2(3,4)"
            modloader: "fabric"

          - artifact: "1.21.4-neoforge"
            target_game_versions: "1.21.2,1.21.3,1.21.4"
            target_game_versions_cf_ids: "12079,12084,12281"
            formatted_version_name: "1.21.2(3,4)"
            modloader: "neoforge"

          - artifact: "1.21.1-fabric"
            target_game_versions: "1.21,1.21.1"
            target_game_versions_cf_ids: "11457,11779"
            formatted_version_name: "1.21(.1)"
            modloader: "fabric"

          - artifact: "1.21.1-neoforge"
            target_game_versions: "1.21,1.21.1"
            target_game_versions_cf_ids: "11457,11779"
            formatted_version_name: "1.21(.1)"
            modloader: "neoforge"

          # --- 1.20.x ---
          - artifact: "1.20.6-fabric"
            target_game_versions: "1.20.5,1.20.6"
            target_game_versions_cf_ids: "11163,11198"
            formatted_version_name: "1.20.5(6)"
            modloader: "fabric"

          - artifact: "1.20.6-neoforge"
            target_game_versions: "1.20.5,1.20.6"
            target_game_versions_cf_ids: "11163,11198"
            formatted_version_name: "1.20.5(6)"
            modloader: "neoforge"

          - artifact: "1.20.4-fabric"
            target_game_versions: "1.20.2,1.20.3,1.20.4"
            target_game_versions_cf_ids: "10236,10395,10407"
            formatted_version_name: "1.20.2(3,4)"
            modloader: "fabric"

          - artifact: "1.20.1-fabric"
            target_game_versions: "1.20,1.20.1"
            target_game_versions_cf_ids: "9971,9990"
            formatted_version_name: "1.20(.1)"
            modloader: "fabric"

          # --- 1.19.x, 1.18.x, 1.17.x, 1.16.x ---
          - artifact: "1.19.4-fabric"
            target_game_versions: "1.19,1.19.1,1.19.2,1.19.3,1.19.4"
            target_game_versions_cf_ids: "9186,9259,9366,9550,9776"
            formatted_version_name: "1.19.x"
            modloader: "fabric"

          - artifact: "1.18.2-fabric"
            target_game_versions: "1.18,1.18.1,1.18.2"
            target_game_versions_cf_ids: "8830,8857,9008"
            formatted_version_name: "1.18.x"
            modloader: "fabric"

          - artifact: "1.17.1-fabric"
            target_game_versions: "1.17,1.17.1"
            target_game_versions_cf_ids: "8152,8516"
            formatted_version_name: "1.17.x"
            modloader: "fabric"

          - artifact: "1.16.5-fabric"
            target_game_versions: "1.16,1.16.1,1.16.2,1.16.3,1.16.4,1.16.5"
            target_game_versions_cf_ids: "7890,7892,8010,8056,8134,8203"
            formatted_version_name: "1.16.x"
            modloader: "fabric"

    steps:
      - uses: actions/checkout@v4

      - name: Download Artifacts (JARs)
        uses: actions/download-artifact@v4
        with:
          name: Artifacts
          path: gathered-artifacts

      - name: Download CurseForge (lite) Artifacts
        uses: actions/download-artifact@v4
        with:
          name: Artifacts-Lite
          path: gathered-artifacts-lite

      - name: Download Release Notes
        uses: actions/download-artifact@v4
        with:
          name: Release Notes
          path: gathered-artifacts

      - name: Resolve file path and Changelog
        run: |
          file_path=$(ls gathered-artifacts/*${{ matrix.artifact }}*.jar)
          echo "file_path=${file_path}" >> $GITHUB_ENV
          echo "file_path for this version is: $file_path"

          cf_file_path=$(ls gathered-artifacts-lite/*${{ matrix.artifact }}*.jar)
          echo "cf_file_path=${cf_file_path}" >> $GITHUB_ENV
          echo "cf_file_path for this version is: $cf_file_path"
          
          raw_tag_name=${GITHUB_REF#refs/tags/}
          
          # removes the 'v' prefix
          tag_name=${raw_tag_name#v}
          echo "tag_name=${tag_name}" >> $GITHUB_ENV

          changelog=$(cat gathered-artifacts/release_notes.md)
          echo "changelog<<EOF" >> $GITHUB_ENV
          echo "${changelog}" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

          # log prints
          echo "tag_name: $tag_name"
          echo "changelog: $changelog"

      # https://github.com/marketplace/actions/upload-to-modrinth
      - name: Upload to Modrinth
        uses: RubixDev/modrinth-upload@v1
        with:
          token: ${{ secrets.MODRINTH_TOKEN }}
          file_path: ${{ env.file_path }}
          name: "v${{ env.tag_name }}+${{ matrix.formatted_version_name }}+${{ matrix.modloader }}"
          version: ${{ env.tag_name }}
          changelog: ${{ env.changelog }}
          # requires Cloth Config
          relations: "9s6osm5g:required"
          game_versions: ${{ matrix.target_game_versions }}
          release_type: "release"
          loaders: "${{ matrix.modloader }}"
          featured: false
          project_id: "pbnlOdwp"

      # https://github.com/marketplace/actions/upload-to-curseforge
      - name: Upload to CurseForge
        uses: itsmeow/curseforge-upload@v3
        with:
          token: ${{ secrets.CURSEFORGE_TOKEN }}
          project_id: "1453568"
          game_endpoint: "minecraft"
          file_path: ${{ env.cf_file_path }}
          # 7499: Modloader - Fabric, 10150: Modloader - NeoForge, 9638: Environment - Client
          game_versions: "${{ matrix.target_game_versions_cf_ids }},Modloader:${{ matrix.modloader }},9638"
          release_type: "release"
          display_name: "v${{ env.tag_name }}+${{ matrix.formatted_version_name }}+${{ matrix.modloader }}"
          changelog: ${{ env.changelog }}
          changelog_type: "markdown"
          relations: "cloth-config:requiredDependency"
